# Generated by Django 5.1.1 on 2024-10-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionschedule',
            name='route',
        ),
        migrations.AddField(
            model_name='collectionschedule',
            name='waste_type',
            field=models.CharField(choices=[('plastic', 'Plastic'), ('iron', 'Iron'), ('paper', 'Paper'), ('e-waste', 'E-Waste'), ('aluminum', 'Aluminum'), ('glass', 'Glass')], default='plastic', max_length=20),
        ),
    ]
