# Generated by Django 5.1.2 on 2024-10-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_slotbooking_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
