# Generated by Django 5.1.1 on 2024-10-31 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_wallettransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='rewards',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='manager',
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
