# Generated by Django 5.1.1 on 2024-11-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_wallet_user_alter_wallettransaction_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_fund_transfer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='collected_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='slotbooking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
