# Generated by Django 5.1.1 on 2024-11-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_notification_is_fund_transfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='amount',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
