# Generated by Django 5.1.1 on 2024-11-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_notification_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='collection_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot_bookings', to='core.collectionschedule'),
        ),
    ]
