# Generated by Django 5.1.1 on 2024-11-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_slotbooking_collection_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotbooking',
            name='collection_schedule',
        ),
    ]
