# Generated by Django 5.1.1 on 2024-10-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionschedule',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='CollectionSchedule',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
